---
- name: Check current docker-compose version.
  command: "localectl status"
  register: localectl_status

- block:
    - name: Change keyboard layout to german
      command: "sudo localectl set-x11-keymap de pc105 nodeadkeys compose:rwin"

    - name: propagete changes to system
      command: "sudo update-locale"

    - name: reboot
      reboot:
        msg: "Reboot with ansible ..."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
  when: not localectl_status.stdout_lines is search("de-latin1-nodeadkeys")

# https://wiki.ubuntuusers.de/systemd/localectl/