---
- name: "check if project dir exists"
  stat:
    path: "/home/vagrant/projects/{{ project_name }}"
  register: project_dir

- name: "create project dir if not exists"
  file:
    path: "/home/vagrant/projects/{{ project_name }}"
    state: directory
  when: not project_dir.stat.exists

- name: "checkout repository for devbox"
  git:
    repo: "{{ git_url }}"
    dest: "/home/vagrant/projects/{{ project_name }}"
