---
- hosts: localhost
  connection: local
  strategy: debug

  roles:
    - role: apt-update
    - role: apt-install-items
      packages:
        - vim
        - curl
        - unzip
        - git
        - terminator
    - role: snap-install-items
      packages:
        - notepad-plus-plus
        - firefox
        - intellij-idea-ultimate
    - role: clone-git-public
      git_url: "https://github.com/krec05/dev-box.git"
      project_name: "dev-box"
    - role: intellij-install-plugins
      # https://stackoverflow.com/questions/24044513/intellij-idea-install-plugins-from-command-line

    #- role: docker # TODO need to look at, cause docker ps do not work on dev box
    #- role: guest_additions
